### ISSUE TITLE
AssertionError on TASK [Gathering Facts]

### ISSUE THREAD

**Issue by nbw74** [ansible-community/ansible-bender#130]
#### Install software
CentOS Linux release 7.6.1810 (Core)
podman-0.12.1.2-2.git9551f6b.el7.centos
buildah-1.7.1-2.git93747b1.el7.centos
python36-pip-8.1.2-8.el7
pip3: ansible (2.8.0)
pip3: ansible-bender (0.6.0)
#### Run ansible-bender (as root)
```
sudo ansible-bender --debug build --extra-ansible-args='-vvvvvv' demo.yml
```
### What's the expected result?
Successfull building image and executing all ansible playbook commands
### What's the actual result?
```
[... skip ...]
10:48:37.784 utils.py          DEBUG  PLAY [Demonstration of ansible-bender functionality] **********************************************************************
**************************************
10:48:37.791 utils.py          DEBUG  
10:48:37.791 utils.py          DEBUG  TASK [Gathering Facts] ****************************************************************************************************
**************************************
10:48:37.791 utils.py          DEBUG  task path: /home/gitlab-runner/builds/-8pHB6bA/0/infra/ubuntu-base/.demo-20190519-104835445816-shnkdeiqmy.yaml:1
10:48:37.796 utils.py          DEBUG  10:48:37.795 snapshoter.py     ERROR  error while running the build: 
10:48:37.796 utils.py          DEBUG  10:48:37.796 snapshoter.py     DEBUG  Traceback (most recent call last):
10:48:37.796 utils.py          DEBUG    File "/usr/local/lib/python3.6/site-packages/ansible_bender/callback_plugins/snapshoter.py", line 123, in v2_playbook_on_
task_start
10:48:37.796 utils.py          DEBUG      return self._maybe_load_from_cache(task)
10:48:37.796 utils.py          DEBUG    File "/usr/local/lib/python3.6/site-packages/ansible_bender/callback_plugins/snapshoter.py", line 109, in _maybe_load_fro
m_cache
10:48:37.796 utils.py          DEBUG      content = self.get_task_content(task.get_ds())
10:48:37.796 utils.py          DEBUG    File "/usr/local/lib/python3.6/site-packages/ansible_bender/callback_plugins/snapshoter.py", line 71, in get_task_content
10:48:37.796 utils.py          DEBUG      assert serialized_data
10:48:37.796 utils.py          DEBUG  AssertionError
10:48:37.796 utils.py          DEBUG  
[... skip ...]
```
All tasks in the playbook is skipped
```
10:48:39.793 utils.py          DEBUG  TASK [Run a sample command] ***********************************************************************************************
**************************************
10:48:39.793 utils.py          DEBUG  task path: /home/gitlab-runner/builds/-8pHB6bA/0/infra/ubuntu-base/.demo-20190519-104835445816-shnkdeiqmy.yaml:4
10:48:39.793 utils.py          DEBUG  10:48:39.782 db.py             DEBUG  search for runtime dir
10:48:39.793 utils.py          DEBUG  10:48:39.782 db.py             DEBUG  trying /root/.cache
10:48:39.793 utils.py          DEBUG  10:48:39.782 db.py             DEBUG  runtime dir is /root/.cache
10:48:39.796 utils.py          DEBUG  skipping: [a-very-nice-image-20190519-104834352417-cont] => {
10:48:39.796 utils.py          DEBUG      "changed": false,
10:48:39.797 utils.py          DEBUG      "skip_reason": "Conditional result was False"
10:48:39.797 utils.py          DEBUG  }
```
w/o debug flag:
```
TASK [Gathering Facts] ******************************************************************************************************************************************
12:09:57.406 snapshoter.py     ERROR  error while running the build: 
ok: [a-very-nice-image-20190519-120947267847-cont]

TASK [Run a sample command] *************************************************************************************************************************************
skipping: [a-very-nice-image-20190519-120947267847-cont]

TASK [Stat a file] **********************************************************************************************************************************************
skipping: [a-very-nice-image-20190519-120947267847-cont]

PLAY RECAP ******************************************************************************************************************************************************
a-very-nice-image-20190519-120947267847-cont : ok=1    changed=0    unreachable=0    failed=0    skipped=2    rescued=0    ignored=0   
```
Build successfull, but no ansible tasks executed.

**Comment by jmorrison** [comment]
I saw this, too.  Please advise of any work-around (I am not fussy).

fedora-release-28-6.noarch
Linux jm7 5.0.16-100.fc28.x86_64 #1 SMP Tue May 14 18:22:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
ansible-bender 0.6.0  
ansible        2.8.0  
buildah-1.7-1.git873f001.fc28.x86_64
Python 3.6.8

Tracked it down a little further to:

14:12:32.275 utils.py          DEBUG    File "/home/jm/Docker3/ansible-bender/lib/python3.6/site-packages/ansible_bender/callback_plugins/snapshoter.py", line 71, in get_task_content
14:12:32.275 utils.py          DEBUG      assert serialized_data
14:12:32.275 utils.py          DEBUG  AssertionError

an assertion...

**Comment by TomasTomecek** [comment]
The error is happening in bender's callback plugin (where layering happens). Bender is touching internal ansible structures in some places and it seems that 2.8 release of ansible changed those structures. This needs to be fixed in bender, I hope to fix & release this week - no promises, though.

**Comment by TomasTomecek** [comment]
This is now fixed and released.
