### ISSUE TITLE
"ansible-bender clean" throws an exception

### ISSUE THREAD

**Issue by bmillemathias-1a** [ansible-community/ansible-bender#210]
```
21:54 $ ansible-bender --debug clean
21:56:25.572 db.py             DEBUG  search for runtime dir
21:56:25.573 db.py             DEBUG  trying ~/.cache
21:56:25.574 db.py             DEBUG  runtime dir is /home/bmillemathias/.cache
Cleaning images from database which are no longer present on the disk...
Traceback (most recent call last):
  File "/home/bmillemathias/Code/venv/ansible/lib/python3.7/site-packages/ansible_bender/cli.py", line 371, in _clean
    run_cmd(["podman", "inspect", b.target_image],
NameError: name 'run_cmd' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bmillemathias/Code/venv/ansible/bin/ansible-bender", line 8, in <module>
    sys.exit(main())
  File "/home/bmillemathias/Code/venv/ansible/lib/python3.7/site-packages/ansible_bender/cli.py", line 436, in main
    sys.exit(CLI().run())
  File "/home/bmillemathias/Code/venv/ansible/lib/python3.7/site-packages/ansible_bender/cli.py", line 415, in run
    self._clean()
  File "/home/bmillemathias/Code/venv/ansible/lib/python3.7/site-packages/ansible_bender/cli.py", line 373, in _clean
    except subprocess.CalledProcessError:
NameError: name 'subprocess' is not defined
```
```
21:56 $ ansible-bender --version
0.8.0
```

**Comment by kmehant** [comment]
@bmillemathias-1a 
Hi, this is fixed and merged in to master a couple of days ago. Would be reflected in the coming minor release of ansible-bender. 

_What is the workaround till then?_
You can run ansible-bender directly from your git clone (please make sure that your clone is in sync with upstream with all the latest changes pulled) and run the *CLI* module
``` python3 -m ansible-bender.cli```
Sorry for the trouble.

**Comment by bmillemathias-1a** [comment]
>  Sorry for the trouble.

No problem, I've open the issue in order to help, I forgot to check commit logs.

Best.

**Comment by TomasTomecek** [comment]
I'm planning on releasing a new version this week, before I disappear for the holidays.
